[package]
name = "performance_test_rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2.155"
once_cell = "1.19.0"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.104"
